# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Samuel\Documents\CodingProjects\Python\in_progress\CNC_TOOLBOX\gui\mainwindow.ui',
# licensing of 'C:\Users\Samuel\Documents\CodingProjects\Python\in_progress\CNC_TOOLBOX\gui\mainwindow.ui' applies.
#
# Created: Sat Jan 25 19:11:45 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 671)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.current_file_label = QtWidgets.QLabel(self.centralwidget)
        self.current_file_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_file_label.setObjectName("current_file_label")
        self.gridLayout_3.addWidget(self.current_file_label, 0, 2, 1, 1)
        self.device_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.device_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.device_comboBox.setObjectName("device_comboBox")
        self.gridLayout_3.addWidget(self.device_comboBox, 0, 1, 1, 1)
        self.file_field = QtWidgets.QLineEdit(self.centralwidget)
        self.file_field.setObjectName("file_field")
        self.gridLayout_3.addWidget(self.file_field, 0, 3, 1, 1)
        self.device_label = QtWidgets.QLabel(self.centralwidget)
        self.device_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.device_label.setObjectName("device_label")
        self.gridLayout_3.addWidget(self.device_label, 0, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.gridLayout_3.addWidget(self.save_button, 0, 5, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.save_copy = QtWidgets.QRadioButton(self.widget)
        self.save_copy.setCheckable(True)
        self.save_copy.setChecked(True)
        self.save_copy.setAutoExclusive(True)
        self.save_copy.setObjectName("save_copy")
        self.gridLayout_2.addWidget(self.save_copy, 0, 1, 1, 1)
        self.overwrite_radio = QtWidgets.QRadioButton(self.widget)
        self.overwrite_radio.setObjectName("overwrite_radio")
        self.gridLayout_2.addWidget(self.overwrite_radio, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 4, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 765, 512))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.text_area = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_area.sizePolicy().hasHeightForWidth())
        self.text_area.setSizePolicy(sizePolicy)
        self.text_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_area.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.text_area.setObjectName("text_area")
        self.gridLayout_5.addWidget(self.text_area, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.splitter, 1, 0, 1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.current_file_label.setText(QtWidgets.QApplication.translate("MainWindow", "current file", None, -1))
        self.device_label.setText(QtWidgets.QApplication.translate("MainWindow", "device", None, -1))
        self.save_button.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.save_copy.setText(QtWidgets.QApplication.translate("MainWindow", "copy", None, -1))
        self.overwrite_radio.setText(QtWidgets.QApplication.translate("MainWindow", "overwrite", None, -1))
        self.actionopen.setText(QtWidgets.QApplication.translate("MainWindow", "open", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

